name: Windows

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  raku:
    strategy:
      matrix:
        os:
          - windows-latest
        raku-version:
          - 'latest'
    runs-on: ${{ matrix.os }}

    env:
      # Workaround for path length errors during precompilation of longer repo names
      TMPDIR: /tmp

    steps:
      - uses: actions/checkout@v3
      - uses: Raku/setup-raku@v1
        with:
          raku-version: ${{ matrix.raku-version }}
      - name: Install rak
        run: zef install rak
      - name: Install Dependencies
        run: zef install --/test --test-depends --deps-only .
      - name: Run Special Tests
        run: raku run-tests -i
